import Foundation

// MARK: - Models

struct ZoteroCollection: Identifiable, Codable, Hashable {
    let id: String
    let name: String
    let paperCount: Int

    enum CodingKeys: String, CodingKey {
        case id = "key"
        case name
        case paperCount = "paper_count"
    }
}

struct ZoteroPaper: Identifiable, Codable, Hashable {
    let id: String
    let title: String
    let authors: String
    let year: String
    let abstract: String
    let hasPdf: Bool

    enum CodingKeys: String, CodingKey {
        case id = "key"
        case title
        case authors
        case year
        case abstract
        case hasPdf = "has_pdf"
    }
}

struct MarginaliaNote: Identifiable, Codable, Hashable {
    let id: String
    let paperId: String
    let page: Int
    let content: String
    let noteType: String        // "text" | "voice" | "ink"  — capture origin
    let thoughtType: String     // "note" | "question" | "connection" | "idea" | "disagreement"
    let createdAt: String

    enum CodingKeys: String, CodingKey {
        case id
        case paperId    = "paper_id"
        case page
        case content
        case noteType   = "note_type"
        case thoughtType = "thought_type"
        case createdAt  = "created_at"
    }

    // Custom decoder so that existing notes without thought_type decode as "note"
    // rather than failing. The backend migration adds the column with DEFAULT 'note',
    // but in-flight JSON from an old server won't have the key.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id          = try c.decode(String.self, forKey: .id)
        paperId     = try c.decode(String.self, forKey: .paperId)
        page        = try c.decode(Int.self,    forKey: .page)
        content     = try c.decode(String.self, forKey: .content)
        noteType    = try c.decode(String.self, forKey: .noteType)
        thoughtType = (try? c.decode(String.self, forKey: .thoughtType)) ?? "note"
        createdAt   = try c.decode(String.self, forKey: .createdAt)
    }
}

// Reading intention — user-authored fields attached to a paper.
// Not generated by AI; both fields are optional.
struct PaperContext: Codable {
    let paperId: String
    let reasonSaved: String?
    let readingGoal: String?
    let createdAt: String
    let updatedAt: String

    enum CodingKeys: String, CodingKey {
        case paperId     = "paper_id"
        case reasonSaved = "reason_saved"
        case readingGoal = "reading_goal"
        case createdAt   = "created_at"
        case updatedAt   = "updated_at"
    }
}

// A single AI-generated prompt plus the user's persisted response.
struct Reflection: Identifiable, Codable {
    let id: String
    let paperId: String
    let sourceNoteId: String?
    let reflectionType: String  // "recall" | "revisit" | "resolve" | "close_reading"
    let prompt: String
    var response: String?
    var status: String          // "open" | "answered" | "dismissed"
    let provenance: String      // "model" | "system"
    let createdAt: String
    var answeredAt: String?

    enum CodingKeys: String, CodingKey {
        case id
        case paperId        = "paper_id"
        case sourceNoteId   = "source_note_id"
        case reflectionType = "reflection_type"
        case prompt
        case response
        case status
        case provenance
        case createdAt      = "created_at"
        case answeredAt     = "answered_at"
    }
}

// MARK: - Backend Service

class BackendService {

    static let defaultBaseURL = "http://YOUR-MAC-MINI-TAILSCALE-IP:8000"

    static var baseURL: String {
        let raw = UserDefaults.standard.string(forKey: "backendURL") ?? defaultBaseURL
        return raw.hasSuffix("/") ? String(raw.dropLast()) : raw
    }

    // MARK: Collections

    static func fetchCollections() async throws -> [ZoteroCollection] {
        let url = URL(string: "\(baseURL)/collections")!
        let (data, _) = try await URLSession.shared.data(from: url)
        return try JSONDecoder().decode([ZoteroCollection].self, from: data)
    }

    // MARK: Papers

    static func fetchPapers(collectionId: String) async throws -> [ZoteroPaper] {
        let url = URL(string: "\(baseURL)/collections/\(collectionId)/papers")!
        let (data, _) = try await URLSession.shared.data(from: url)
        return try JSONDecoder().decode([ZoteroPaper].self, from: data)
    }

    static func fetchAllPapers() async throws -> [ZoteroPaper] {
        let url = URL(string: "\(baseURL)/papers")!
        let (data, _) = try await URLSession.shared.data(from: url)
        return try JSONDecoder().decode([ZoteroPaper].self, from: data)
    }

    // MARK: PDF

    static func pdfURL(for paperId: String) -> URL {
        URL(string: "\(baseURL)/papers/\(paperId)/pdf")!
    }

    // MARK: Uploaded Papers

    static func fetchUploadedPapers() async throws -> [ZoteroPaper] {
        let url = URL(string: "\(baseURL)/papers/uploaded")!
        let (data, _) = try await URLSession.shared.data(from: url)
        return try JSONDecoder().decode([ZoteroPaper].self, from: data)
    }

    static func uploadPaper(pdfData: Data, title: String, authors: String, year: String) async throws -> ZoteroPaper {
        let url = URL(string: "\(baseURL)/papers/upload")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        let boundary = UUID().uuidString
        request.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        var body = Data()
        func field(_ name: String, _ value: String) {
            body.append("--\(boundary)\r\n".data(using: .utf8)!)
            body.append("Content-Disposition: form-data; name=\"\(name)\"\r\n\r\n".data(using: .utf8)!)
            body.append("\(value)\r\n".data(using: .utf8)!)
        }
        field("title", title); field("authors", authors); field("year", year)
        // Use the actual title as the filename so the backend can fall back to it
        // if FastAPI reads the title from the multipart filename rather than the form field.
        let safeFilename = title
            .components(separatedBy: CharacterSet(charactersIn: "/\\:*?\"<>|"))
            .joined(separator: "_")
        body.append("--\(boundary)\r\n".data(using: .utf8)!)
        body.append("Content-Disposition: form-data; name=\"pdf\"; filename=\"\(safeFilename).pdf\"\r\n".data(using: .utf8)!)
        body.append("Content-Type: application/pdf\r\n\r\n".data(using: .utf8)!)
        body.append(pdfData)
        body.append("\r\n--\(boundary)--\r\n".data(using: .utf8)!)
        request.httpBody = body
        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(ZoteroPaper.self, from: data)
    }

    static func deleteUploadedPaper(paperId: String) async throws {
        let url = URL(string: "\(baseURL)/papers/uploaded/\(paperId)")!
        var request = URLRequest(url: url)
        request.httpMethod = "DELETE"
        _ = try await URLSession.shared.data(for: request)
    }

    // MARK: Notes

    static func fetchNotes(paperId: String) async throws -> [MarginaliaNote] {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/notes")!
        let (data, _) = try await URLSession.shared.data(from: url)
        return try JSONDecoder().decode([MarginaliaNote].self, from: data)
    }

    static func deleteNote(paperId: String, noteId: String) async throws {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/notes/\(noteId)")!
        var request = URLRequest(url: url)
        request.httpMethod = "DELETE"
        _ = try await URLSession.shared.data(for: request)
    }

    static func updateNote(paperId: String, noteId: String, content: String) async throws -> MarginaliaNote {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/notes/\(noteId)")!
        var request = URLRequest(url: url)
        request.httpMethod = "PATCH"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try JSONSerialization.data(withJSONObject: ["content": content])
        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(MarginaliaNote.self, from: data)
    }

    // thoughtType defaults to "note" so all existing call-sites are unaffected.
    static func saveNote(
        paperId: String,
        page: Int,
        content: String,
        noteType: String,
        thoughtType: String = "note"
    ) async throws -> MarginaliaNote {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/notes")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        let body: [String: Any] = [
            "paper_id": paperId,
            "page": page,
            "content": content,
            "note_type": noteType,
            "thought_type": thoughtType,
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)
        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(MarginaliaNote.self, from: data)
    }

    // MARK: Paper context (reading intention)

    // Returns nil if no context has been set yet for this paper.
    static func fetchContext(paperId: String) async throws -> PaperContext? {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/context")!
        let (data, response) = try await URLSession.shared.data(from: url)
        if let http = response as? HTTPURLResponse, http.statusCode == 404 { return nil }
        // Backend returns JSON null when no context exists
        if let str = String(data: data, encoding: .utf8), str.trimmingCharacters(in: .whitespaces) == "null" {
            return nil
        }
        return try JSONDecoder().decode(PaperContext.self, from: data)
    }

    static func upsertContext(
        paperId: String,
        reasonSaved: String?,
        readingGoal: String?
    ) async throws -> PaperContext {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/context")!
        var request = URLRequest(url: url)
        request.httpMethod = "PUT"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var body: [String: Any] = [:]
        if let r = reasonSaved { body["reason_saved"] = r }
        if let g = readingGoal { body["reading_goal"] = g }
        request.httpBody = try JSONSerialization.data(withJSONObject: body)
        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(PaperContext.self, from: data)
    }

    // MARK: Reflections

    static func fetchReflections(paperId: String) async throws -> [Reflection] {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/reflections")!
        let (data, _) = try await URLSession.shared.data(from: url)
        return try JSONDecoder().decode([Reflection].self, from: data)
    }

    static func generateReflections(paperId: String, mode: String = "recall") async throws -> [Reflection] {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/reflections/generate")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = 120
        request.httpBody = try JSONSerialization.data(withJSONObject: ["mode": mode])
        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode([Reflection].self, from: data)
    }

    static func updateReflection(
        paperId: String,
        reflectionId: String,
        response: String? = nil,
        status: String? = nil
    ) async throws -> Reflection {
        let url = URL(string: "\(baseURL)/papers/\(paperId)/reflections/\(reflectionId)")!
        var request = URLRequest(url: url)
        request.httpMethod = "PATCH"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var body: [String: Any] = [:]
        if let r = response { body["response"] = r }
        if let s = status   { body["status"]   = s }
        request.httpBody = try JSONSerialization.data(withJSONObject: body)
        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(Reflection.self, from: data)
    }

    // MARK: Voice Transcription

    static func transcribeAudio(audioData: Data) async throws -> String {
        let url = URL(string: "\(baseURL)/transcribe")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.timeoutInterval = 300
        let boundary = UUID().uuidString
        request.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        var body = Data()
        body.append("--\(boundary)\r\n".data(using: .utf8)!)
        body.append("Content-Disposition: form-data; name=\"audio\"; filename=\"recording.m4a\"\r\n".data(using: .utf8)!)
        body.append("Content-Type: audio/m4a\r\n\r\n".data(using: .utf8)!)
        body.append(audioData)
        body.append("\r\n--\(boundary)--\r\n".data(using: .utf8)!)
        request.httpBody = body
        let (data, _) = try await URLSession.shared.data(for: request)
        let result = try JSONDecoder().decode([String: String].self, from: data)
        return result["text"] ?? ""
    }
}
